FROM golang:alpine as builder
ADD src/ /opt/src/
WORKDIR /opt/src/
RUN go get -d -v
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o goapp

FROM alpine
COPY --from=builder /opt/src/goapp /opt/app/
WORKDIR /opt/app/
ENTRYPOINT ./goapp
