version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    entrypoint: sh
    # entrypoint: go run main.go
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./src:/opt/src
